config/routes.rb
Calagator::Engine.routes.draw do
  match 'omfg' => 'site#omfg'
  match 'hello' => 'site#hello'

  match 'about' => 'site#about'

  match 'opensearch.:format' => 'site#opensearch'
  match 'defunct' => 'site#defunct'

  match 'admin' => 'admin#index'
  get "admin/index"
  get "admin/events"
  match "lock_event" => "admin#lock_event", :only => :post

  resources :events do
    collection do
      post :squash_many_duplicates
      get :search
      get :duplicates
      match 'tag/:tag', via: :get, to: :search, as: :tag
    end

    member do
      get :clone
    end
  end

  resources :sources do
    collection do
      post :import
    end
  end

  resources :venues do
    collection do
      post :squash_many_duplicates
      get :map
      get :duplicates
      get :autocomplete
      match 'tag/:tag', via: :get, to: :search, as: :tag
    end
  end

  resources :versions, :only => [:edit]
  resources :changes, :controller => 'paper_trail_manager/changes'
  match 'recent_changes' => redirect("/changes")
  match 'recent_changes.:format' => redirect("/changes.%{format}")

  match 'css/:name' => 'site#style'
  match 'css/:name.:format' => 'site#style'

  match '/' => 'site#index', :as => :root
  match '/index' => 'site#index'
  match '/index.:format' => 'site#index'
end

app/models/calagator/event.rb
# == Schema Information
# Schema version: 20110604174521
#
# Table name: events
#
#  id              :integer         not null, primary key
#  title           :string(255)
#  description     :text
#  start_time      :datetime
#  url             :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  venue_id        :integer
#  source_id       :integer
#  duplicate_of_id :integer
#  end_time        :datetime
#  version         :integer
#  rrule           :string(255)
#  venue_details   :text
#

require "calagator/blacklist_validator"
require "calagator/duplicate_checking"
require "calagator/decode_html_entities_hack"
require "calagator/strip_whitespace"
require "calagator/url_prefixer"
require "paper_trail"
require "loofah-activerecord"
require "loofah/activerecord/xss_foliate"

# == Event
#
# A model representing a calendar event.

module Calagator
class Event < ActiveRecord::Base
  self.table_name = "events"

  attr_protected

  has_paper_trail
  acts_as_taggable

  xss_foliate :strip => [:title], :sanitize => [:description, :venue_details]
  include DecodeHtmlEntitiesHack

  # Associations
  belongs_to :venue, :counter_cache => true
  belongs_to :source

  # Validations
  validates_presence_of :title, :start_time
  validate :end_time_later_than_start_time
  validates_format_of :url,
    :with => /\Ahttps?:\/\/(\w+:?\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?\Z/,
    :allow_blank => true,
    :allow_nil => true

  validates :title, :description, :url, blacklist: true

  before_destroy :verify_lock_status

  # Duplicates
  include DuplicateChecking
  duplicate_checking_ignores_attributes    :source_id, :version, :venue_id
  duplicate_squashing_ignores_associations :tags, :base_tags, :taggings

  # Named scopes
  scope :after_date, lambda { |date|
    where(["start_time >= ?", date]).order(:start_time)
  }
  scope :on_or_after_date, lambda { |date|
    time = date.beginning_of_day
    where("(start_time >= :time) OR (end_time IS NOT NULL AND end_time > :time)",
      :time => time).order(:start_time)
  }
  scope :before_date, lambda { |date|
    time = date.beginning_of_day
    where("start_time < :time", :time => time).order(:start_time)
  }
  scope :future, lambda { on_or_after_date(Time.zone.today) }
  scope :past, lambda { before_date(Time.zone.today) }
  scope :within_dates, lambda { |start_date, end_date|
    if start_date == end_date
      end_date = end_date + 1.day
    end
    on_or_after_date(start_date).before_date(end_date)
  }

  scope :future_with_venue, -> {
    future.order("start_time ASC").non_duplicates.includes(:venue)
  }
  scope :past_with_venue, -> {
    past.order("start_time DESC").non_duplicates.includes(:venue)
  }

  # Expand the simple sort order names from the URL into more intelligent SQL order strings
  scope :ordered_by_ui_field, lambda{|ui_field|
    case ui_field
      when 'name'
        order('lower(events.title), start_time')
      when 'venue'
        includes(:venue).order('lower(venues.title), start_time')
      else # when 'date', nil
        order('start_time')
    end
  }

  #---[ Overrides ]-------------------------------------------------------

  # Return the title but strip out any whitespace.
  def title
    # TODO Generalize this code so we can use it on other attributes in the different model classes. The solution should use an #alias_method_chain to make sure it's not breaking any explicit overrides for an attribute.
    read_attribute(:title).to_s.strip
  end

  # Return description without those pesky carriage-returns.
  def description
    # TODO Generalize this code so we can reuse it on other attributes.
    read_attribute(:description).to_s.gsub("\r\n", "\n").gsub("\r", "\n")
  end

  def url=(value)
    super UrlPrefixer.prefix(value)
  end

  # Set the start_time to the given +value+, which could be a Time, Date,
  # DateTime, String, Array of Strings, or nil.
  def start_time=(value)
    super time_for(value)
  rescue ArgumentError
    errors.add :start_time, "is invalid"
    super nil
  end

  # Set the end_time to the given +value+, which could be a Time, Date,
  # DateTime, String, Array of Strings, or nil.
  def end_time=(value)
    super time_for(value)
  rescue ArgumentError
    errors.add :end_time, "is invalid"
    super nil
  end

  def time_for(value)
    value = value.join(' ') if value.kind_of?(Array)
    value = Time.zone.parse(value) if value.kind_of?(String) # this will throw ArgumentError if invalid
    value
  end
  private :time_for

  def lock_editing!
    update_attribute(:locked, true)
  end

  def unlock_editing!
    update_attribute(:locked, false)
  end

  #---[ Queries ]---------------------------------------------------------

  # Return Hash of Events grouped by the +type+.
  def self.find_duplicates_by_type(type='na')
    case type.to_s.strip
    when 'na', ''
      { [] => future }
    else
      kind = %w[all any].include?(type) ? type.to_sym : type.split(',').map(&:to_sym)
      find_duplicates_by(kind,
        :grouped => true,
        :where => "a.start_time >= #{connection.quote(Time.now - 1.day)}")
    end
  end

  #---[ Searching ]-------------------------------------------------------

  # NOTE: The `Event.search` method is implemented elsewhere! For example, it's
  # added by SearchEngine::ActsAsSolr if you're using that search engine.

  def self.search_tag(tag, opts={})
    includes(:venue).tagged_with(tag).ordered_by_ui_field(opts[:order])
  end

  def self.search(query, opts={})
    SearchEngine.search(query, opts)
  end

  #---[ Transformations ]-------------------------------------------------

  def location
    venue && venue.location
  end

  def venue_title
    venue && venue.title
  end

  #---[ Date related ]----------------------------------------------------

  # Returns an array of the dates spanned by the event.
  def dates
    raise ArgumentError, "can't get dates for an event with no start time" unless start_time
    if end_time
      (start_time.to_date..end_time.to_date).to_a
    else
      [start_time.to_date]
    end
  end

  # Is this event current?
  def current?
    (end_time || start_time) >= Date.today.to_time
  end

  # Is this event old?
  def old?
    (end_time || start_time + 1.hour) <= Time.zone.now.beginning_of_day
  end

  # Did this event start before today but ends today or later?
  def ongoing?
    start_time < Date.today.to_time && end_time && end_time >= Date.today.to_time
  end

  def duration
    if end_time && start_time
      (end_time - start_time)
    else
      0
    end
  end

protected

  def end_time_later_than_start_time
    if start_time && end_time && end_time < start_time
      errors.add(:end_time, "cannot be before start")
    end
  end

  def verify_lock_status
    return !locked
  end
end

end

app/models/calagator/event/cloner.rb
# Return a new record with fields selectively copied from the original, and
# the start_time and end_time adjusted so that their date is set to today and
# their time-of-day is set to the original record's time-of-day.
module Calagator

class Event < ActiveRecord::Base
  class Cloner < Struct.new(:event)
    def self.clone(event)
      new(event).clone
    end

    ATTRIBUTES = [:title, :description, :venue_id, :url, :tag_list, :venue_details]

    def clone
      clone = Event.new
      ATTRIBUTES.each do |attribute|
        clone.send "#{attribute}=", event.send(attribute)
      end
      if event.start_time
        clone.start_time = clone_time_for_today(event.start_time)
      end
      if event.end_time
        clone.end_time = clone_time_for_today(event.end_time)
      end
      clone
    end

    private

    # Return a time that's today but has the time-of-day component from the
    # +source+ time argument.
    def clone_time_for_today(source)
      today = Date.today
      Time.zone.local(today.year, today.mon, today.day, source.hour, source.min, source.sec, source.usec)
    end
  end
end

end

app/models/calagator/event/ical_renderer.rb
# Return an iCalendar string representing an Array of Event instances.
#
# Arguments:
# * :events - Event instance or array of them.
#
# Options:
# * :url_helper - Lambda that accepts an Event instance and generates a URL
#   for it if it doesn't have a URL already.
#
# Example:
#   ics1 = Event::IcalRenderer.render(myevent)
#   ics2 = Event::IcalRenderer.render(myevents, url_helper: -> (event) { event_url(event) })
module Calagator

class Event < ActiveRecord::Base
  class IcalRenderer
    def self.render(events, opts={})
      output = render_icalendar(events, opts)
      output = add_name(output)
      output = normalize_line_endings(output)
    end

    def self.render_icalendar(events, opts)
      RiCal.Calendar do |calendar|
        calendar.prodid = "-//Calagator//EN"

        Array(events).each do |event|
          calendar.event do |entry|
            new(event, opts).add_event_to(entry)
          end
        end
      end.export
    end

    def self.add_name(output)
      output.sub(/(CALSCALE:\w+)/i, "\\1\nX-WR-CALNAME:#{Calagator.title}\nMETHOD:PUBLISH")
    end

    def self.normalize_line_endings(output)
      output.gsub(/\r?\n/,"\r\n")
    end

    attr_reader :event, :imported_from

    def initialize(event, opts)
      @event = event
      @imported_from = opts[:url_helper].call(event).to_s if opts[:url_helper]
    end

    def add_event_to(entry)
      fields.each do |field|
        value = send(field)              # value = summary
        entry.send field, value if value # entry.summary summary if summary
      end
    end

    private

    def fields
      %w(summary description url location dtstart dtend created last_modified sequence dtstamp uid)
    end

    def summary
      event.title || 'Untitled Event'
    end

    def description
      parts = [
        description_range,
        description_description,
        description_tags,
        description_imported_from,
      ].compact

      parts.join if parts.any?
    end

    def description_range
      return unless multiday?
      time_range = TimeRangeHelper.normalize_time(event, format: :text)
      "This event runs from #{time_range}.\n\nDescription:\n"
    end

    def description_description
      Loofah::Helpers.strip_tags(event.description) if event.description.present?
    end

    def description_tags
      "\n\nTags: #{event.tag_list}" if event.tag_list.present?
    end

    def description_imported_from
      "\n\nImported from: #{imported_from}" if imported_from
    end

    def url
      event.url if event.url.present?
    end

    def location
      [event.venue_title, event.venue.full_address].compact.join(": ") if event.venue
    end

    def dtstart
      if multiday?
        event.dates.first
      else
        event.start_time
      end
    end

    def dtend
      if multiday?
        event.dates.last + 1.day
      else
        event.end_time || event.start_time + 1.hour
      end
    end

    def created
      event.created_at if event.created_at
    end

    def last_modified
      event.updated_at if event.updated_at
    end

    def sequence
      # Set the iCalendar SEQUENCE, which should be increased each time an
      # event is updated. If an admin needs to forcefully increment the
      # SEQUENCE for all events, they can edit the "config/secrets.yml"
      # file and set the "icalendar_sequence_offset" value to something
      # greater than 0.
      (SECRETS.icalendar_sequence_offset || 0) + event.versions.count
    end

    def dtstamp
      # dtstamp and uid added because of a bug in Outlook;
      # Outlook 2003 will not import an .ics file unless it has DTSTAMP, UID, and METHOD
      # use created_at for DTSTAMP; if there's no created_at, use event.start_time;
      event.created_at || event.start_time
    end

    def uid
      imported_from
    end

    # Treat any event with a duration of at least 20 hours as a multiday event.
    def multiday?
      event.dates.size > 1 && event.duration.seconds > 20.hours
    end
  end
end

end

app/models/calagator/event/overview.rb
module Calagator

class Event < ActiveRecord::Base
  class Overview
    def today
      Event.non_duplicates.within_dates(today_date, tomorrow_date)
    end

    def tomorrow
      Event.non_duplicates.within_dates(tomorrow_date, after_tomorrow_date)
    end

    def later
      Event.non_duplicates.within_dates(after_tomorrow_date, future_cutoff_date)
    end

    def more
      Event.after_date(future_cutoff_date).first
    end

    def tags
      @tags ||= Event.tag_counts_on(:tags, limit: 100, conditions: "tags_count >= 10").sort_by(&:name)
    end

    private

    def today_date
      @today_date ||= Time.zone.now.beginning_of_day
    end

    def tomorrow_date
      today_date + 1.day
    end

    def after_tomorrow_date
      tomorrow_date + 1.day
    end

    def future_cutoff_date
      today_date + 2.weeks
    end
  end
end

end

app/models/calagator/event/saver.rb
module Calagator

class Event < ActiveRecord::Base
  class Saver < Struct.new(:event, :params, :failure)
    def save
      event.attributes = params[:event]
      event.venue      = find_or_initialize_venue
      event.start_time = [ params[:start_date], params[:start_time] ]
      event.end_time   = [ params[:end_date], params[:end_time] ]
      event.tags.reload # Reload the #tags association because its members may have been modified when #tag_list was set above.

      attempt_save?
    end

    def has_new_venue?
      return unless event.venue
      event.venue.previous_changes["id"] == [nil, event.venue.id] && params[:venue_name].present?
    end

    private

    def find_or_initialize_venue
      if params[:event] && params[:event][:venue_id].present?
        Venue.find(params[:event][:venue_id]).progenitor
      else
        Venue.find_or_initialize_by_title(params[:venue_name]).progenitor
      end
    end

    def attempt_save?
      !spam? && !preview? && event.save
    end

    def spam?
      evil_robot? || too_many_links?
    end

    def evil_robot?
      if params[:trap_field].present?
        self.failure = "<h3>Evil Robot</h3> We didn't save this event because we think you're an evil robot. If you're really not an evil robot, look at the form instructions more carefully. If this doesn't work please file a bug report and let us know."
      end
    end

    def too_many_links?
      if event.description.present? && event.description.scan(/https?:\/\//i).size > 3
        self.failure = "We allow a maximum of 3 links in a description. You have too many links."
      end
    end

    def preview?
      if params[:preview]
        event.valid?
      end
    end
  end
end

end

app/models/calagator/event/search.rb
module Calagator

class Event < ActiveRecord::Base
  class Search < Struct.new(:query, :tag, :order, :current)
    def initialize attributes = {}
      members.each do |key|
        send "#{key}=", attributes[key]
      end
      self.order ||= "date"
      validate!
    end

    # Return +events+ grouped by currentness using a data structure like:
    #
    #   {
    #     :current => [ my_current_event, my_other_current_event ],
    #     :past => [ my_past_event ],
    #   }
    def grouped_events
      grouped = events.group_by(&:current?)
      grouped = { current: grouped[true] || [], past: grouped[false] || [] }
      grouped[:current].reverse! if order.to_s == "date"
      grouped[:past] = [] if current
      grouped
    end

    def current
      ["1", "true"].include?(super)
    end

    def events
      @events ||= if tag
        Event.search_tag(tag, order: order, current: current)
      else
        Event.search(query, order: order, skip_old: current)
      end
    end

    def failure_message
      @failure_message
    end

    def hard_failure?
      @hard_failure
    end

    private

    def validate!
      unless %w(date name title venue score).include?(order) || order.blank?
        @failure_message = "Unknown ordering option #{order.inspect}, sorting by date instead."
      end

      if tag.present? && order == "score"
        @failure_message = "You cannot sort tags by score"
      end

      if [query, tag].all?(&:blank?)
        @failure_message = "You must enter a search query"
        @hard_failure = true
      end

      if [query, tag].all?(&:present?)
        # TODO make it possible to search by tag and query simultaneously
        @failure_message = "You can't search by tag and query at the same time"
        @hard_failure = true
      end
    end
  end
end

end

app/views/calagator/venues/_subnav.html.erb
<div id="venues_subnav" class="subnav">
    <ul class="clearfix">
      <li><%= link_to 'Browse venues', venues_url, 
              :class => subnav_class_for("venues", "index") %>
      </li>
      <li><%= link_to 'Add a venue', new_venue_url,
              :class => subnav_class_for("venues", "new") %>
      </li>
    </ul>
</div>

app/views/calagator/venues/duplicates.html.erb
<%= content_for :title, "Duplicate Venue Squasher" %>

<div id="venues_duplicates">
  <h1>Duplicate Venues</h1>

  <div id='list_filters' class='sidebar'>
    <h3>Show venues with a duplicate</h3>
    <ul>
      <li><%= link_to_unless_current "Title", url_for(:action => 'duplicates', :type => 'title') %></li>
      <li><%= link_to_unless_current "Address", url_for(:action => 'duplicates', :type => 'address') %></li>
      <li><%= link_to_unless_current "Street Address", url_for(:action => 'duplicates', :type => 'street_address') %></li>
      <li><%= link_to_unless_current "Postal Code", url_for(:action => 'duplicates', :type => 'postal_code') %></li>
      <li><%= link_to_unless_current "URL", url_for(:action => 'duplicates', :type => 'url') %></li>
      <li><%= link_to_unless_current "Description", url_for(:action => 'duplicates', :type => 'description') %></li>
      <li><%= link_to_unless_current "Geo. Coords", url_for(:action => 'duplicates', :type => 'latitude,longitude') %></li>
      <li><%= link_to_unless_current "Email", url_for(:action => 'duplicates', :type => 'email') %></li>
      <li><%= link_to_unless_current "Telephone", url_for(:action => 'duplicates', :type => 'telephone') %></li>
      <li>-----</li>
      <li><%= link_to_unless_current "Any Field", url_for(:action => 'duplicates', :type => 'any') %></li>
      <li><%= link_to_unless_current "All Fields", url_for(:action => 'duplicates', :type => 'all') %></li>
    </ul>
    <h3>List venues</h3>
    <ul>
      <li><%= link_to_unless_current "All Venues", url_for(:action => 'duplicates', :type => 'na') %></li>
    </ul>
  </div>

  <% unless @grouped_venues.empty? %>
    <%= form_tag :action => "squash_many_duplicates", :method => :post %>
      <div class="flash notice">
        Select only one set of master and duplicate venues. If you select an unrelated venue, it will be merged into the same single master record.
      </div>
      <div class='list_items'>
        <%= hidden_field_tag(:type, @type) %>
        <table>
          <% for value, group in @grouped_venues %>
            <tr>
              <th>Master?</th><th>Duplicate?</th><th># of Events</th><th>Venue<%= " (#{value})" unless value.blank? %></th>
            </tr>
            <% for venue in group %>
              <tr class="<%= cycle('odd', 'even') %>">
                <td><%= radio_button_tag("master_id", venue.id) %></td>
                <td><%= check_box_tag("duplicate_id_#{venue.id}", venue.id) %></td>
                <td><%= venue.events_count %></td>
                <td>
                  <%= link_to(venue.title, venue_url(venue)) %>
                  <% if venue.has_full_address? %>
                    at <%= venue.full_address %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
        <ul>
          <li>Checked items will be deleted.</li>
          <li>Events associated with deleted venues will be replaced with the venues selected using radio buttons.</li>
        </ul>
        <%= submit_tag "Squash Duplicates" %>
      </div>
    </form>
  <% else %>
    No duplicates found
  <% end %>
</div>

app/views/calagator/venues/edit.html.erb
<%= content_for :title, "Editing #{@venue.title}" %>

<%= render 'calagator/versions/edit_with_chooser', :record => @venue %>

app/views/calagator/venues/index.html.erb
<%= content_for :title, "Venues" %>

<% tabindex_on '#search_field' %>

<div id="venues_index">
<h1>Venues</h1>
<div id='venues_search'>
  <h2>Find a venue:</h2>
  <%= form_tag venues_path, :method => 'get' do %>
    <div class='keywords'>
      <%= label_tag :query, "Keywords" %>
      <%= text_field_tag :query, @search.query %>
    </div>
    <div class='wifi'>
      <%= check_box_tag :wifi, '1', @search.wifi %>
      <%= label_tag :wifi, "Public WiFi" %>
    </div>

    <div class='submit'>
      <%= submit_tag "Search" %>
    </div>
  <% end %>
</div>

<% if @search.results? %>
  <div id='venues_search_results'>
    <div class='list_description'>
      <% if @search.tag %>
        <h2>Showing <strong><%= @venues.size %></strong> venues tagged with <strong><%= @search.tag %></strong></h2>
      <% else -%>
        <h2>
          <% if @venues.size == 0 -%>
            Sorry, there are no venues
          <% else -%>
            Showing <%= "all " if @search.all %><strong><%= @venues.size %></strong> <%= 'venue'.pluralize(@venues.size) %>
          <% end %>
          <% if @search.query.present? %>
            matching &#8220;<%= @search.query %>&#8221;
          <% end %>
          <%= "with public WiFi" if @search.wifi %>
        </h2>
      <% end -%>
    </div>

    <ul>
      <% @venues.each do |venue| %>
        <li>
          <%= link_to(venue.title, venue_url(venue)) %>
          <% if venue.has_full_address? %>
            <p class='detail'><%= venue.full_address %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div id='venue_portal'>
    <div id='most_active'>
      <h3>Most Active</h3>
      <ul>
        <% @search.most_active_venues.each do |venue| %>
          <li>
            <%= link_to(venue.title, venue_url(venue)) %>
            <p class='detail'><%= venue.events_count %> events</p>
          </li>
        <% end %>
      </ul>
    </div>
    <div id='newest'>
      <h3>Newest</h3>
      <ul>
        <% @search.newest_venues.each do |venue| %>
          <li>
            <%= link_to(venue.title, venue_url(venue)) %>
            <p class='detail'>Added <%= time_ago_in_words(venue.created_at) %> ago</p>
          </li>
        <% end %>
      </ul>
    </div>
    <div id="exports">
      <ul>
        <li><%= link_to 'List all venues', venues_path(:all => 1) %></li>
        <li><%= link_to 'View a big map', map_venues_path %></li>
      </ul>
      <h3>Export venues</h3>
      <ul>
        <li><%= link_to 'KML', '/venues.kml' %></li>
        <li><%= link_to 'JSON', '/venues.json' %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/calagator/venues/index.kml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
  <Document>
  <% for venue in @venues -%>
  <% next if venue.latitude.nil? -%>
  <Placemark>
    <name><%= escape_once(venue.title) %></name>
    <description><%= cdata_section(venue.description) %></description>
    <Point>
      <coordinates><%= venue.longitude %>,<%= venue.latitude %></coordinates>
    </Point>
  </Placemark>
  <% end -%>
  </Document>
</kml>

app/views/calagator/venues/map.html.erb
<h1>Big Map of Venues</h1>
<div id='venues_map'>
  <%= map @venues, Calagator.venues_map_options %>
</div>

app/views/calagator/venues/new.html.erb
<%= content_for :title, "Add a Venue" %>

<div id="new_venue_form">
  <%= render :partial => 'form', :locals => {:venue => @venue} %>
</div>

app/views/calagator/venues/show.html.erb
<%= content_for :title, @venue.title %>

<% tabindex_on '#search_field' %>

<% content_for :discovery_insert do %>
  <link rel="alternate" type="application/x-wiki" title="Edit this page" href="<%= edit_venue_url(@venue) %>" />
<% end %>

<div class="single_venue contentbar">
  <a href="#" id="venue_sidebar_toggle" class="expander_toggle">Export or edit this venue...</a>
  <div id="venue_sidebar" class='single_view_right sidebar'>
    <div id='edit_link'>
      <p>
        You can <%= link_to "edit", edit_venue_url(@venue) %>
        or <%= link_to "delete", venue_url(@venue), :method => :delete, :confirm => "Are you sure?" %>
        this venue.
      </p>
    </div>
    <hr />
    <p>Download an <%= link_to "iCalendar file", venue_url(@venue, :format => :ics) %> or
    <%= link_to "subscribe to a feed", venue_url(@venue, :format => :ics, :protocol => "webcal") %> of events at this venue.</p>
    <hr />
    <div class="metadata">
      <%= datestamp(@venue) %>
    </div>
  </div>

  <div class="location vcard<%= " closed" if @venue.closed? %>">
    <h1 class="fn org"><%= @venue.title %></h1>
    <% if @venue.closed? %><p class='closed_callout'>This venue is no longer open for business.</p><% end %>

    <% if @venue.has_full_address? %>
      <div class="adr">
        <% if @venue.street_address.present? %>
          <div class="street-address"><%= @venue.street_address %></div>
        <% end %>
        <% if @venue.locality.present? %>
          <span class="locality"><%= @venue.locality %></span><%= "," if @venue.region.present? or @venue.postal_code.present? or @venue.country.present? %>
        <% end %>
        <% if @venue.region.present? %>
          <span class="region"><%= @venue.region %></span><%= "," if @venue.country.present? and not @venue.postal_code.present? %>
        <% end %>
        <% if @venue.postal_code.present? %>
          <span class="postal-code"><%= @venue.postal_code %></span><%= "," if  @venue.country.present? %>
        <% end %>
        <% if @venue.country.present? %>
          <span class='country-name'><%= @venue.country %></span>
        <% end %>
        (<a href='<%=google_maps_url(@venue.full_address) -%>'>map</a>)
      </div>
    <% else %>
      <% if @venue.address.present? %>
        <div class='address'>
          <%= @venue.address %>
          (<a href='<%=google_maps_url(@venue.address) -%>'>map</a>)
        </div>
      <% end %>
    <% end %>

    <div class='info'>
      <% if @venue.url.present? %>
        <div class='url'><%= link_to(truncate(url_for(@venue.url), :length => 60), url_for(@venue.url), :rel => "nofollow") %></div>
      <% end %>

      <% if @venue.email.present? %>
        <div class='email'><%= mail_to @venue.email %></div>
      <% end %>

      <% if @venue.telephone.present? %>
        <div class='tel'><%= @venue.telephone %></div>
      <% end %>

      <% if @venue.wifi? %>
        <div class='wifi_callout'>Public WiFi</div>
      <% end %>
    </div>
  </div>

  <% if @venue.description.present? || @venue.access_notes.present? %>
    <div class="description">
      <%= format_description(@venue.description) %>
      <% if @venue.access_notes.present? %>
        <div class="access_notes">
          <h3>Access Notes</h3>
          <%= format_description @venue.access_notes %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @venue.tags.present? -%>
    <div class="tags">
      <h2>Tags</h2>
      <%= tag_links_for @venue %>
    </div>
  <% end %>

  <div id="google_map">
    <%= map @venue %>
  </div>

  <div id='events'>
    <div id='future_events'>
      <h2>Future events happening here</h2>
      <%= render :partial => 'calagator/events/list', :locals => { :events => @venue.future_events } %>
    </div>

    <div id='past_events'>
      <h2>Past events that happened here</h2>
      <%= render :partial => 'calagator/events/list', :locals => { :events => @venue.past_events } %>
    </div>
  </div>
</div>